services:
  - type: web
    name: beautylab-consulenza
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FACEPP_API_KEY
        sync: false
      - key: FACEPP_API_SECRET
        sync: false
